const longString = '''
In the quiet town of Elderglen, nestled between rolling hills and dense forests, a peculiar mystery unfolded one autumn. Sophie Merritt, a girl who preferred books over play, stumbled upon a strange library deep in the woods. This ivy-covered building, hidden behind a rusted gate, seemed alive with whispers and secrets.
Inside, Sophie found towering shelves of ancient books and a red leather tome on a pedestal. Its single inscription read, "To uncover the truth, light the flame of memory." Suddenly, a booming voice declared, “Who dares awaken the Library of Echoes?” Sophie introduced herself, and the voice softened, guiding her to a hidden chamber.
In this chamber stood a golden hourglass surrounded by murals of Elderglen's history. Each mural depicted pivotal moments in the town's past—battles fought, alliances forged, and moments of joy and sorrow. One mural, however, was cracked and incomplete, as though erased by time itself. The voice revealed this missing fragment held a stolen memory of the town. “A truth forgotten to protect the guilty,” it said. To restore it, Sophie needed to retrieve the Ember of Remembrance, hidden deep within the forest and guarded by shadows.
Guided by faint glowing trails that weaved through the forest like threads of light, Sophie embarked on her quest. The woods grew darker and colder as she ventured further, the air heavy with an ominous energy. In a hidden glade, Sophie found the ember, pulsing like a heartbeat atop a small pedestal. But as she approached, shadowy figures emerged from the surrounding darkness, their forms twisting and shifting like smoke. They moved to block her path, their presence cold and menacing.
Sophie's pulse quickened. Remembering the book's inscription, she tore a strip of cloth from her scarf, wrapped it around a sturdy branch, and ignited it using the ember's glow. The makeshift torch flared brightly, its warm light cutting through the encroaching shadows. With a final surge of courage, Sophie grasped the ember and fled the glade, the shadows retreating into the forest.
Back at the library, Sophie placed the ember within the golden hourglass. The shimmering sands began to flow, filling the cracks in the mural. Slowly, the missing scene revealed itself: a tale of betrayal and redemption. It depicted a forgotten hero who had saved Elderglen from ruin but had been erased from history by those who sought to claim the glory for themselves. The library's voice resonated with gratitude. “You have restored what was lost. Elderglen's story is whole again.”
Before she left, the library offered Sophie a final gift. A small, glowing crystal appeared in her hands, its light pulsating softly. “This is a shard of memory,” the voice explained. “It will guide you to stories that need to be told.” Sophie tucked the crystal into her pocket, feeling its warmth against her skin.
When Sophie emerged from the forest, the harvest festival was in full swing. The townsfolk, dressed in their finest autumn colors, danced and feasted under strings of glowing lanterns. Sophie hurried to the town square and recounted her journey to her family and neighbors.
Her vivid tale of the mysterious library, the ancient murals, and the shadowy guardians left the townsfolk in awe. When Sophie revealed the story of the forgotten hero, an elderly woman in the crowd whispered, “That's Rowan the Brave. My grandmother spoke of him, but no one believed it.”
From that day forward, Sophie was known as the Keeper of Stories. Though she never found the Library of Echoes again, its whispers stayed with her, urging her to inspire others to seek the untold and forgotten truths.
''';

final mediumString =
    longString.substring(0, longString.lastIndexOf('memory."'));

final smallString = longString.substring(0, longString.indexOf('.'));
